default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails
  host: 127.0.0.1

development:
  <<: *default
  database: short_messages_development

test:
  <<: *default
  database: short_messages_test

production:
  <<: *default
  database: short_messages_production
  username: short_messages
  password: <%= ENV["SHORT_MESSAGES_DATABASE_PASSWORD"] %>
